### ISSUE TITLE
[2.7.x] [typescript] Type inference breaks under specific circumstances

### ISSUE THREAD

**Issue by last-partizan** [vuejs/vue#12628]
### Version
2.7.3

### Reproduction link
[github.com](https://github.com/last-partizan/vue-examples/tree/4608c5527c81d367fa44ec4932ef6120940c3e70)

Or just create this file in minimal vue-ts (v2) project

```ts
import {defineComponent} from "vue";
// Replace vue import with this, and it woks fine.
//import {defineComponent} from "@vue/composition-api";

import App from "./App.vue";

export default defineComponent({
  components: {
    App,
  },
  data() {
    return {};
  },
  provide(): any {
    return {
      fetchData: this.fetchData,
    };
  },
  created() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      throw new Error("Not implemented.");
    },
  },
});

```

### Steps to reproduce
Clone example repo, run `pnpm install`, run `pnpm vue-tsc --noEmit`

### What is expected?
No errors.

### What is actually happening?
Has ts errors.

```
src/broken-method-type.ts:15:23 - error TS2339: Property 'fetchData' does not exist on type 'CreateComponentPublicInstance<{}, unknown, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

15       fetchData: this.fetchData,
                         ~~~~~~~~~

src/broken-method-type.ts:19:10 - error TS2339: Property 'fetchData' does not exist on type 'CreateComponentPublicInstance<{}, unknown, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

19     this.fetchData();
            ~~~~~~~~~


Found 2 errors in the same file, starting at: src/broken-method-type.ts:15
```

---
I'm updating our app from `vue-2.6 + @vue/composition-api` to `vue-2.7`, and after update i see many type checking erros.

If you replace import from "vue" to import from "@vue/composition-api", it works fine.

If you remove `data` or `components`, it works fine.

**Comment by chearon** [comment]
I can't get props to infer to anything other than `any` or `never` either. Simple repro here: johnsoncodehk/volar#1537

**Comment by yyx990803** [comment]
closed via 1d5a411c
@JorisAerts your issues should be fixed by d3add06e & f8de4ca9

**Comment by JorisAerts** [comment]
> closed via [1d5a411](https://github.com/vuejs/vue/commit/1d5a411c1e3aa062aa5080432cf3f852f1583ed2) @JorisAerts your issues should be fixed by [d3add06](https://github.com/vuejs/vue/commit/d3add06e6e18a78a3745240632fecd076eb49d19) & [f8de4ca](https://github.com/vuejs/vue/commit/f8de4ca9d458a03378e848b1e62d6507f7124871)

Great, thanks!

**Comment by last-partizan** [comment]
Thanks, https://github.com/vuejs/vue/commit/1d5a411c1e3aa062aa5080432cf3f852f1583ed2 is indeed fixed case when component is `App: defineComponent({})`, but it did not fix case when component is imported from another file, like:

```ts
import App from "./App.vue";
```

I've updated vue to 2.7.4 in my example repo, error is still here.
https://github.com/last-partizan/vue-examples/tree/f2c659c3757a2457d344cc5786031a1298de35a1

**Comment by last-partizan** [comment]
@yyx990803 please reopen this, it isn't fixed yet.

https://github.com/last-partizan/vue-examples/tree/11c64acb67a3aaba788f6e4275405b2cc37d1f5a

With `2.7.5` error is still here.

```
pnpm vue-tsc
src/broken-method-type.ts:16:23 - error TS2339: Property 'fetchData' does not exist on type 'CreateComponentPublicInstance<{}, unknown, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

16       fetchData: this.fetchData,
                         ~~~~~~~~~

src/broken-method-type.ts:20:10 - error TS2339: Property 'fetchData' does not exist on type 'CreateComponentPublicInstance<{}, unknown, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

20     this.fetchData();
            ~~~~~~~~~


Found 2 errors in the same file, starting at: src/broken-method-type.ts:16
```

**Comment by johuhype** [comment]
For components that do not use props, it is possible to fix this by putting the data() part at the very bottom of the defineComponent declaration. 
For component with props, I did not manage to use it at all yet.

**Comment by Ansett** [comment]
We just made the move to replace all `data()` references by refs in `setup()` in our old components.
It was tedious but it's a step forward migration :p
No issue with methods' typing when there is no `data()`, even when there are props

**Comment by eeedvisss** [comment]
We can confirm that after moving from `2.6 + composition-api` to `2.7` types in `methods` only work if we move `data` property to the bottom(after `methods`) or change `data` to arrow function:

This doesnt work anymore:
![image](https://user-images.githubusercontent.com/20832646/196657235-ba02d090-2da1-4073-9e5b-0a430ca4b48c.png)

This works:
![image](https://user-images.githubusercontent.com/20832646/196656939-216c8d15-aca3-4038-bbd6-762813b89e65.png)

And this works:
![image](https://user-images.githubusercontent.com/20832646/196657336-fe0e8f9b-e037-4af3-bc05-945e98b1d5f9.png)

Are we missing something here? 
Or is this a bug in type support?

**Comment by jorisvergeer** [comment]
I also have this problem, also changing the data to an arrow function works around it but then i cannot acces props in the data function:
![image](https://user-images.githubusercontent.com/1906639/200823347-4cde69d1-d710-4959-a68d-418f3c884d60.png)
![image](https://user-images.githubusercontent.com/1906639/200823397-6321814c-8991-4af8-b92a-bfa1fcefb17a.png)

Type inference is also broken when the data arrow function has an this argument:
![image](https://user-images.githubusercontent.com/1906639/200824649-08204609-51f5-4ba2-93aa-881f239074d2.png)

Only works with data arrow function without this zrgument:
![image](https://user-images.githubusercontent.com/1906639/200824805-a6656344-5b50-408d-812f-c30c9868d803.png)

**Comment by gionkunz** [comment]
What's the state of this issue? I have found type support pretty useless with this issue. My defined components seem to have no inference for `this`. In `mounted`, `emits` and `computed`,  `this` is always typed as any. Only the template picks up the types correctly.

```
<template>
  <div>
    {{person.name}}
    ({{personWithAge}})
    <button @click="incrementCount()">Count</button>
    {{count}}
  </div>
</template>

  <script lang="ts">

  import { defineComponent, PropType } from 'vue';

  export interface Person {
    name: string;
    age: number;
  }

  export default defineComponent({
    props: {
      person: Object as PropType<Person>
    },
    data() {
      return {
        count: 0,
      };
    },
    computed: {
      personWithAge() {
        return `${this.person.name} is ${this.person.age} years old`;
      }
    },
    methods: {
      incrementCount() {
        this.count++;
      }
    }
  });
  </script>
  ```

![vue-defined-comp-type-issues](https://user-images.githubusercontent.com/2203704/217677602-f272e325-3975-4bc6-b69f-16a4830f68ed.gif)

The GIF above shows that props, data and computed are typed correctly in the template. However, incrementCount is not found on the inferred type. Within the component definition, however, nothing is typed and even `this` is inferred as `any`.

The CLI does not complain, and everything works as expected at runtime.

I'm using Vue 2.7.14 and Vetur v0.36.1 in VSCode.

**Comment by axetroy** [comment]
This bug still exists in 2.7.14

**Comment by asmaloney** [comment]
Just ran into this with 2.7.14 as well.

A lot of instances of error **TS2339**.

I tried all the solutions here. Replacing `data(): Data {` with `data: (): Data => {` solved the TS2339 errors, but then I can't reference `this` in the data section.

If I follow the vue 2 docs and take `instance` as a param (`data: (instance): Data => {`), then that works, but it breaks with TS2339 errors again.

So I have exactly the same problem as @jorisvergeer [mentions above](https://github.com/vuejs/vue/issues/12628#issuecomment-1308642782).

I feel like I'm going around in circles and cannot figure out how to make this work. Is there a working solution somewhere?

**Comment by drew-royster** [comment]
This is still broken for me in 2.7.14 and I installed vue-tsc ^1.2.0

**Comment by gcaaa31928** [comment]
I think we should reopen this issue ?

**Comment by zcf0508** [comment]
https://github.com/vuejs/vue/pull/13063

**Comment by tskimmett** [comment]
Still experiencing this issue. Moving `data` after `methods` or using an arrow function for `data` works around the issue. Very odd.

**Comment by backrunner** [comment]
Still got lots of TS2339 errors in `2.7.16`, seems like this problem won't be fixed anymore...
