### ISSUE TITLE
Vue.compile is not a function

### ISSUE THREAD

**Issue by melbayad** [vuejs/vue#3972]
I am using Vuejs 2 (webpack-simple template) and I would compile template before render it. Below my code :
**App.vue**
```javascript
<template>
    <div id="app">
        <h1>{{ msg }}</h1>
    </div>
</template>
<script>
    export default {
        name: 'app'
    }
</script>
```

**main.js**
```javascript
import Vue from 'vue'
import App from './App.vue'

const res = Vue.compile(App)
const vm = new Vue({
    el: '#app',
    data: {
        msg: 'hello'
    },
    render: res.render,
    staticRenderFns: res.staticRenderFns
})
```

But when I start the server I got this error : `__WEBPACK_IMPORTED_MODULE_0_vue___default.a.compile is not a function` . Can you please help me to make it work ?

**Comment by LinusBorg** [comment]
`import Vue from 'vue'`imports the runtime-only build, which does not have the compiler.

https://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

I will adjust the template to include the standalone build version by default.

**Comment by LinusBorg** [comment]
Done. https://github.com/vuejs-templates/webpack-simple/commit/de7d7d75bd8646e8df38d61c3046b7c229d8cf02

**Comment by melbayad** [comment]
@LinusBorg Thanks for your reply. As mentioned above, I added the `vue$` alias to my webpack config but It didn't resolve the problem. I got another error : `template.trim is not a function` (in vue.js, line : `7023`)

**Comment by LinusBorg** [comment]
Oh. Now this is a different problem, and a mistake on your part which I didn't catch before:

* `Vue.compile()` expects a template string
*  you pass the component `App` to it
* but `App` is a object of component options, and its template has aready been compiled into a render function by vue-loader

**Comment by melbayad** [comment]
Ok... @LinusBorg, I get your point. So, The main goals for me :  
* Separate component content to `main.js` to keep code clean. 
* I don't want to have html content in script tag
So, If I keep just the content inside the `<template>` tag in my 'App' component, is there any way to get its content as `String` in `main.js` ?

**Comment by LinusBorg** [comment]
> So, If I keep just the content inside the `<template>` tag in my 'App' component, is there any way to get its content as `String` in `main.js` ? 

No. The whole point of vue files is to keep everything in one place. Why do you want an App.vue component if you only want the template string?

And I don't really understand what you are trying to do, or why, despite your explanation. Sorry :(

**Comment by melbayad** [comment]
This is the real scenario : I would like to compile components in nodejs project then render it in Java project. This is what I'm trying to do... but as compile function accept just string param I think It wouldn't be relevant for me. Thanks a lot @LinusBorg for your detailed explanation.
