### ISSUE TITLE
virtual dom style problem

### ISSUE THREAD

**Issue by u0024window** [vuejs/vue#4279]
1.use v-for render template , when array delete splice one, the virtual dom will delete last elememt,causing the css chaos 
2. 复杂结构的组件用v-for 渲染，当数组改变是，样式会偏移
eg,
var arr = [object, object];
```
<div v-if="xxx">
  <div  v-show="xxx" id="one"></div>
</div>
<div else>
  <div id="two"></div>
</div>
```
数组删除第一个元素，div#two 会有display:none,出现

**Comment by yyx990803** [comment]
Cannot reproduce in latest version. I think this has been fixed a while ago, you are likely using an old version.

**Comment by u0024window** [comment]
yesterday，i use vue#2.0.8, 
I have always been concerned about the Vue version，hope fix that
today, i update the new vue2.1.0, still have the problem （css chaos）

**Comment by u0024window** [comment]
@yyx990803

**Comment by fnlctrl** [comment]
If so, please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!
