### ISSUE TITLE
Client-side rendered virtual DOM tree is not matching server-rendered content when using async components

### ISSUE THREAD

**Issue by fenivana** [vuejs/vue#4387]
Here is the minimal code that can reproduce the error, just run in browser:
The JSFiddle: http://jsfiddle.net/fenivana/58s5x2kb/

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
  </head>

  <body>
    <div id="app" server-rendered="true"><div class="foo">foo</div></div>

    <script>
    new Vue({
      el: '#app',

      template: '<div id="app"><foo></foo></div>',

      components: {
        foo: resolve => {
          setTimeout(() => {
            resolve({
              template: '<div class="foo">foo</div>'
            });
          });
        }
      }
    });
    </script>
  </body>
</html>
```

If you comment out `setTimeout`, there's no problem.
```js
resolve => {
  // setTimeout(() => {
    resolve({
      template: '<div class="foo">foo</div>'
    });
  // });
}
```

Of course, the code splitting point in real code is in the router, and only client entry bundle will do code splitting, not server entry bundle.

**Comment by HerringtonDarkholme** [comment]
Hi @fenivana, thanks for filing this! I really like your issue reporting style, succinct yet informing :)

I have a fix for this, and tried it with small demo and it worked well. But I wonder if it can work on larger application. So would you like to give #4506 a local build and try it with your application? Thanks!

**Comment by yyx990803** [comment]
This is addressed in `vue-router@2.2` by using `router.onReady` on both client and server to ensure async components are resolved before render/hydration. Ad-hoc use of async components without the router, however, will likely not be supported.

**Comment by fracasula** [comment]
@yyx990803 I'm still getting it once I upgraded to 2.5.2 and router 3.0.1 => https://github.com/vuejs/vue/issues/6825

Unfortunately I can't use CodeSandbox as it's giving me a 500 but there isn't much code to look at anyway, hope it's fine.

**Comment by LinusBorg** [comment]
@fracasula You are not using [`router.onReady`](https://router.vuejs.org/en/api/router-instance.html#methods)
