### ISSUE TITLE
2.2.1 problem, not happening in 2.1.0

### ISSUE THREAD

**Issue by rayoplateado** [vuejs/vue#5015]
I'm just deploying an app, working in a stage server pretty well. But now i have moved into my production server an I found this error:

```
TypeError: Cannot read property 'split' of undefined
    at w (vendor.fd8c17e024793a3406a8.js:12)
    at new Da (vendor.fd8c17e024793a3406a8.js:13)
    at ke (vendor.fd8c17e024793a3406a8.js:12)
    at be (vendor.fd8c17e024793a3406a8.js:12)
    at o.e._init (vendor.fd8c17e024793a3406a8.js:12)
    at new o (vendor.fd8c17e024793a3406a8.js:12)
    at Ae (vendor.fd8c17e024793a3406a8.js:12)
    at Ce (vendor.fd8c17e024793a3406a8.js:12)
    at o (vendor.fd8c17e024793a3406a8.js:12)
    at a (vendor.fd8c17e024793a3406a8.js:12)
a @ vendor.fd8c17e024793a3406a8.js:13
```
My RC version of vue is 2.1.0 but my production version is 2.2.1
RC is working perfectly.

Moving back to 2.1.0 by the moment!

**Comment by rayoplateado** [comment]
I'm trying to force to 2.2.1, but see this on `npm run build`
```
ERROR in 

Vue packages version mismatch:

- vue@2.1.0
- vue-template-compiler@2.2.1
```

**Comment by amertum** [comment]
If using `^` prefix in npm` package.json` version, vuejs 2.1 is auto-updated to version 2.2. A workaround is to force the version of npm package. Remove the `^` from` "vue-template-compiler": "2.1.3"` and other identified package. I really don't like this `^` feature in npm as the build must be predictable and reproducible.

**Comment by yyx990803** [comment]
Re-installing `vue-loader` should fix this problem. This is a bug in `vue-hot-reload-api` that has already been fixed.

**Comment by rayoplateado** [comment]
Thank you guys!

**Comment by Zwaen91** [comment]
Having all versions hardcoded but still getting version mismatch.
```
- vue@2.1.10
- vue-template-compiler@2.1.3
```
package.json
```
"gulp": "3.9.1",
"laravel-elixir": "6.0.0-15",
"laravel-elixir-vue-2": "0.3.0",
"laravel-elixir-webpack-official": "1.0.10",
"lodash": "4.17.4",
"vue": "2.1.10"
```

**Comment by Akryum** [comment]
@Zwaen91 add `vue-template-compiler` version to your `package.json` so that it matches the `vue` version:

```
npm install --save-dev vue-template-compiler@2.1.10
```

**Comment by sotaan** [comment]
I'm still getting this error when updating from '2.1.5' to '2.2.5' even when I updated `vue-loader` to latest (11.3.2).
Help!!!!
