### ISSUE TITLE
Function-type props broken in TypeScript

### ISSUE THREAD

**Issue by kjleitz** [vuejs/vue#9357]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/keegan_openbay/gehkx7pf/10/](https://jsfiddle.net/keegan_openbay/gehkx7pf/10/)

(More explanation in the fiddle, but keep in mind that JSFiddle doesn't show TS errors)

### Steps to reproduce
1. Declare a prop of type `Function`, and with a default function that returns some value; e.g.,

```ts
// ...
  props: {
    fooFn: {
      type: Function,
      default: () => true,
    },
  },
// ...
```

2. Try to use that function elsewhere in your component options; e.g.,

```ts
// ...
  methods: {
    useFooFn(): void {
      const bar = this.fooFn();
      // ...
    },
  },
// ...
```

### What is expected?
```ts
type FooFn = typeof this.fooFn; // Function
this.fooFn(); // no errors
```

### What is actually happening?
```ts
type FooFn = typeof this.fooFn; // boolean | Function
this.fooFn();
// Cannot invoke an expression whose type lacks a call signature.
// Type 'boolean | Function' has no compatible call signatures.
```

---
Vue version: 2.5.22
TypeScript version: 3.0.3

tsconfig.json:

```json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es7", "dom"],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "baseUrl": "./app/javascript",
    "noImplicitThis": true
  },
  "include": [
    "app/javascript/**/*.ts",
    "app/javascript/**/*.tsx",
    "app/javascript/**/*.vue"
  ],
  "exclude": [
    "**/*.spec.ts",
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by posva** [comment]
I tried adding the test case to the project and couldn't reproduce:

```ts
Vue.extend({
  props: {
    isValid: {
      type: Function,
      default: () => true,
    }
  },
  methods: {
    useFooFn(): void {
      const bar = this.isValid()
      alert(bar)
    }
  }
});
```

**Comment by kjleitz** [comment]
@posva Are you using the same TypeScript setup and seeing no compile errors?

**Comment by posva** [comment]
no, I'm using the one we have in the repo

**Comment by kjleitz** [comment]
Can you try with the setup I posted?

**Comment by kjleitz** [comment]
![screen shot 2019-01-23 at 3 45 55 pm](https://user-images.githubusercontent.com/18669659/51635963-06835780-1f26-11e9-8a1c-1a6173d04406.png)


![screen shot 2019-01-23 at 3 45 12 pm](https://user-images.githubusercontent.com/18669659/51635914-eeabd380-1f25-11e9-94e8-95158e23b8bd.png)

**Comment by kjleitz** [comment]
@posva I uncovered a clue:

I just downgraded `vue` (and `vue-template-compiler`) to *2.5.17* and it works fine, as it used to. Then I upgraded both to `2.5.18`, and now I see a bunch of compiler errors (including this one) which had never occurred before:

```ts
// for Function-type props with a default like `() => false`, `(arg: number) => false`, etc.:
// => TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'boolean | Function' has no compatible call signatures.
// (same error occurs with any return value)

function foo(barEl: HTMLElement) { /* ... */ }
foo(this.$el);
// => TS2345: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.

const bar = this.$el.innerText;
// => TS2339: Property 'innerText' does not exist on type 'Element'.
```

Seems that:

1. Function props' types are being recognized as either `Function` _or_ the return type of their `default` function
1. The type of `this.$el` has become `Element` instead of `HTMLElement`
1. This occurs in `vue`/`vue-template-compiler` 2.5.18+, but not 2.5.17

It may have something to do with `"noImplicitThis": true` in `tsconfig.json`; setting it to `false` removes all those errors (there is one new error in our project after setting it to `false` but it's to do with a lack of type inference on `this.$store`, all in one component rather than scattered across the project)

**Comment by kjleitz** [comment]
Reverting https://github.com/vuejs/vue/pull/8537, specifically this change:

```diff
diff --git a/types/options.d.ts b/types/options.d.ts
index cc58affe6a..25eb8a0fdf 100644
--- a/types/options.d.ts
+++ b/types/options.d.ts
@@ -133,7 +133,7 @@ export type PropValidator<T> = PropOptions<T> | Prop<T> | Prop<T>[];
 export interface PropOptions<T=any> {
   type?: Prop<T> | Prop<T>[];
   required?: boolean;
-  default?: T | null | undefined | (() => object);
+  default?: T | null | undefined | (() => T | null | undefined);
   validator?(value: T): boolean;
 }
```

...fixes the `Function`-type prop issue.

**Comment by kjleitz** [comment]
And reverting https://github.com/vuejs/vue/pull/8809, specifically this change:

```diff
diff --git a/types/vue.d.ts b/types/vue.d.ts
index 44a892ead3..3832f2c9e4 100644
--- a/types/vue.d.ts
+++ b/types/vue.d.ts
@@ -21,7 +21,7 @@ export interface CreateElement {
 }
 
 export interface Vue {
-  readonly $el: HTMLElement;
+  readonly $el: Element;
   readonly $options: ComponentOptions<Vue>;
   readonly $parent: Vue;
   readonly $root: Vue;
```

...fixes the `this.$el` defaulting to `Element` issue.

**Comment by kjleitz** [comment]
I'll see if I can write up a PR.

**Comment by kjleitz** [comment]
Furthermore, if you want to return an _object_ from the default, it _completely_ skips the function type altogether:

```ts
// ...

  props: {
    returnsAnObject: {
      type: Function,
      default: () => ({}),
    }
  },

// ...

  // Type SHOULD be `Function`, or `() => {}`, but...
  this.returnsAnObject; //=> Type: {}
  // ...which is not even the [broken] union `{} | () => {}` type like the other cases

  this.returnsAnObject();
  // Cannot invoke an expression whose type lacks a call signature.
  // Type '{}' has no compatible call signatures.

// ...
```

**Comment by kjleitz** [comment]
I'd rather not add to this, since at this point it's an echo chamber, but this `5.2.17` to `5.2.18+` _patch_ (!) update breaks our build, necessitates a lot of boilerplate around what used to be correctly-inferred properties on our components. Any attention would be greatly appreciated!

**Comment by pikax** [comment]
if you annotate with the `PropType<>` it should work, this was a fix on https://github.com/vuejs/vue/pull/9733

```ts
const Example = Vue.extend({
	template: `
  	<button @click="doSomethingWithFoo()">
    	<slot></slot>
    </button>
  `,

  props: {
    // original issue
    fooFn: {
      type: Function as PropType<()=>string>,
      default: () => { return 'hey this is the default return value'; },
    },


     returnsAnObject: {
      type: Function as PropType<()=>object>,
      default: () => ({}),
    }
  },

  methods: {
    doSomethingWithFoo(): void {
      const obj = this.returnsAnObject(); //obj is object
    	const bar = this.fooFn(); // bar is string
  
      alert(bar);
    },
  },
});
```


there's an PR https://github.com/vuejs/vuejs.org/pull/2068 to update docs

**Comment by romansp** [comment]
@kjleitz I'm sure that it does work on TS 3.5.3 and Vue 2.6.10. You can try cloning my repro https://github.com/romansp/vue-typescript-prop-function-default. I just pushed `ts-3.5.3 branch` where `vue serve` runs fine.

**Comment by kjleitz** [comment]
@romansp Ah, I see, you're not using the same `tsconfig.json` as in my original example. The fact that you're using `"strict": true` instead of `"noImplicitThis": true` fixes it in your `ts-3.5.3` branch (we've also switched to using `"strict": true` since the time this ticket was written; much better!). Even with `"strict": true` though, if you set Vue back to v2.6.8 it's actually still broken in your `ts-3.5.3` branch. It's always been wonky.

Vue v2.6.10 & TS v3.5.3 must be one of those special combinations that don't error for function props 🤷‍♂ But even in that branch, the "working" case loses type info from `this.cb`—better to use `type: Function as PropType<() => void>,` instead of a bare `type: Function,`.

**Comment by kjleitz** [comment]
This is still broken, even with `"strict": true`; can't use a `default` for a function-type prop. A more complete example:

```ts
const ComponentWithFunctionProps = Vue.extend({
  props: {
    functionProp: {
      type: Function,
      default: () => true,
    },
    functionPropWithBooleanReturnType: {
      type: Function as PropType<() => boolean>,
      default: () => true,
    },
    booleanProp: {
      type: Boolean,
      default: true,
    },
    booleanPropWithFunctionDefault: {
      type: Boolean,
      default: () => true,
    },
  },
  methods: {
    test(): void {
      // ERROR!
      // (property) functionProp: boolean | Function
      // -------------------------------------------
      // This expression is not callable.
      //   No constituent of type 'boolean | Function' is callable.ts(2349)
      this.functionProp();

      // ERROR!
      // (property) functionPropWithBooleanReturnType: boolean | (() => boolean)
      // -----------------------------------------------------------------------
      // This expression is not callable.
      //   Not all constituents of type 'boolean | (() => boolean)' are callable.
      //     Type 'false' has no call signatures.ts(2349)
      this.functionPropWithBooleanReturnType();

      // const foo: boolean
      const foo = this.booleanProp;

      // const bar: boolean
      const bar = this.booleanPropWithFunctionDefault;
    },
  },
});
```

I submitted a fix for this in https://github.com/vuejs/vue/pull/11223.

**Comment by cqsd** [comment]
I believe several of the type errors you're seeing are due to this: https://vuejs.org/v2/guide/components-props.html#Prop-Validation (if `.default` is a function, it is called to produce the default value.)

I fixed it by wrapping the default function prop in its own factory function, like this:
```vue
<script lang="ts">
import Vue, { PropType } from 'vue'

const foo = (): string => 'foo'

export default Vue.extend({
  props: {
    fooProp: {
      type: Function as PropType<() => string>,
      // type: Function, // also works
      default: () => foo,
    },
  },
  data() {
    const bar = this.fooProp() // this compiles
    return { bar }
  },
})
</script>
```
